language: python

jobs:
  include:
    - name: "Python 3.6 on Ubuntu"
      python: 3.6
    - name: "Python 3.7 on Ubuntu"
      python: 3.7
    - name: "Python 3.8 on Ubuntu"
      python: 3.8
    - name: "Python 3.6.8 on Windows"
      os: windows
      language: shell
      before_install:
        - choco install python --version 3.6.8
        - python -m pip install --upgrade pip
      env: PATH=/c/Python36:/c/Python36/Scripts:$PATH
    - name: "Python 3.7.2 on Windows"
        os: windows
        language: shell
        before_install:
          - choco install python --version 3.7.2
          - python -m pip install --upgrade pip
      env: PATH=/c/Python37:/c/Python37/Scripts:$PATH
    - name: "Python 3.8.2 on Windows"
        os: windows
        language: shell
        before_install:
          - choco install python --version 3.8.2
          - python -m pip install --upgrade pip
      env: PATH=/c/Python38:/c/Python38/Scripts:$PATH

install:
  - pip install -r requirements.txt
  - pip install .[test]

script:
#  - python -m unittest discover -s unittests -p "test_*.py"
  - python -m pytest unittests

notifications:
  email:
    recipients:
      - mikecokina@gmail.com
      - mirofedurco@gmail.com
    on_success: always
    on_failure: always

branches:
  only:
  - pre04_code_review
  - master
  - dev
  - /^release.*$/
