language: python

jobs:
  include:
    - name: "Python 3.6 on Ubuntu"
      python: 3.6
    - name: "Python 3.6.8 on Windows"
      os: windows
      language: shell
      before_install:
        - choco install python --version 3.6.8
        - python -m pip install --upgrade pip
      env: PATH=/c/Python36:/c/Python36/Scripts:$PATH

install:
  - pip install -r requirements.txt
  - pip install .[test]

script:
#  - python -m unittest discover -s unittests -p "test_*.py"
  - python -m pytest unittests

notifications:
  email:
    recipients:
      - mikecokina@gmail.com
      - mirofedurco@gmail.com
    on_success: always
    on_failure: always

branches:
  only:
  - pre04_code_review
  - master
  - dev
  - /^release.*$/
