language: python

jobs:
  include:
    - name: "Python 3.6.X on Windows"
      os: windows
      language: shell
      before_install:
        - choco install python --version 3.6.12
        - python -m pip install --upgrade pip
      env: PATH=/c/Python36:/c/Python36/Scripts:$PATH

#python:
#  - "3.6"

install:
  - pip3 install -r requirements.txt
  - pip3 install .[test]

script:
#     - python -m unittest discover -s unittests -p "test_*.py"
    - python3 -m pytest unittests

notifications:
  email:
    recipients:
      - mikecokina@gmail.com
      - mirofedurco@gmail.com
    on_success: always
    on_failure: always

branches:
  only:
  - pre04_code_review
  - master
  - dev
  - /^release.*$/
