language: python

os:
  - windows

python:
  - "3.6"

before_install:
    - if [ "$TRAVIS_OS_NAME" = "windows" ]; choco install python3; fi
    - if [ "$TRAVIS_OS_NAME" = "windows" ]; export PATH="/c/Python38:/c/Python38/Scripts:$PATH"; fi

install:
  - pip install -r requirements.txt
  - pip install .[test]

script:
  - python -m unittest discover -s unittests -p "test_*.py"

notifications:
  email:
    recipients:
      - mikecokina@gmail.com
      - mirofedurco@gmail.com
    on_success: always
    on_failure: always

branches:
  only:
  - pre04_code_review
  - master
  - dev
  - /^release.*$/
