language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
install:
  - pip install -r requirements.txt
  - pip install .[test]
# command to run tests

script:
  - python -m unittest discover -s unittests -p "test_*.py"

notifications:
  email:
    recipients:
      - mikecokina@gmail.com
      - mirofedurco@gmail.com
    on_success: always
    on_failure: always

branches:
  only:
  - master
  - dev
  - /^release.*$/
